feature[fiar]menambahkan router order
BingleShop-Team-1/BingleShop-Team1 pull request #3
Opened 2024-03-25 14:59 UTC by NisfiSNF

menambahkan router order (dan index.js pada folder router)

2024-03-25 15:44 UTC, syaifuladala approved these changes

2024-03-25 17:23 UTC, CarlitoDon approved these changes

2024-03-25 22:04 UTC, Mojjitt0o requested changes
Pada router.post bisa diberikan try-catch block buat nangkap kesalahan kalau ngk bisa terhubung atau menyimpan pesanan di database .

Untuk coding bisa dipastikan dulu memakai tanda titik koma ( ; )  tidak .

2024-03-26 01:54 UTC, Mojjitt0o approved these changes

2024-03-26 03:21 UTC, merged